### ISSUE TITLE
Opt-out button for Trackers Preview

### ISSUE THREAD

**Issue by chrmod** [whotracksme/webextension-packages#4]
On the Trackers Preview we want to have a button to disable this feature. It should send a message to extension background - the background will decide how to implement the settings.

Visually, the button itself should be added to Trackers Preview:
<img width="365" alt="Screenshot 2022-01-26 at 17 21 48" src="https://user-images.githubusercontent.com/1228153/151203113-35831be6-a8af-43a6-a49e-5946777f6524.png">

and can look like links in the footer of Ghostery 9 popup:
<img width="342" alt="Screenshot 2022-01-26 at 17 22 31" src="https://user-images.githubusercontent.com/1228153/151203249-c7000e93-a16d-4c8c-92cf-0ddc6fe86566.png">

It should say "Disable Trackers Preview" - the text should come from translations.

Additionally we should replace text "Trackers on this site" with "Trackers Preview", it should also come from translations.

**Comment by smalluban** [comment]
@chrmod The description looks promising.
