### ISSUE TITLE
Trackers preview wheel covers the menu button on search result page

### ISSUE THREAD

**Issue by smalluban** [whotracksme/webextension-packages#9]
It looks that is some conditions google search result page renders the three-dot menu button, which is covered by our tracker wheel:

<img width="919" alt="Zrzut ekranu 2022-02-7 o 10 03 35" src="https://user-images.githubusercontent.com/1906677/152759732-05c6185e-cd4e-48e5-be28-f5dbd1e548ca.png">

**Comment by philipp-classen** [comment]
Looks like the assumptions about the position are off in that situation:

https://github.com/whotracksme/webextension-packages/blob/3b850bbaa354b2870341f028e4d3693991b07d99/packages/serp-report/src/content_scripts/serp-report.js#L85
